apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  selector:
    app: nodejs-cicd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-cicd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-cicd
  template:
    metadata:
      labels:
        app: nodejs-cicd
    spec:
      containers:
        - name: nodejs-container
          image: ajeesh2000/node-js-1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


